# Site settings
title: Your Site Title
description: > # this means to ignore newlines until "baseurl:"
  A brief description of your site goes here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourdomain.com" # the base hostname & protocol for your site

# Author settings
author:
  name: Your Name
  email: your-email@example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: /:categories/:title/

# Pagination
paginate: 5 # Number of posts per page
paginate_path: "/page/:num/"

# Social links (optional)
social_links:
  twitter: your_twitter_handle
  github: your_github_username
  linkedin: your_linkedin_username
